### PR TITLE
Fixes #42 - Correct app crash when app was installed from Google Play (using AAB)

### LINKED ISSUE #42: Apps installed from Google Play using AAB format crash on start
**Describe the bug**
Since August 2021, new apps that are uploaded to Google Play must use the AAB format.
But apps that are uploaded as AAB and then installed from Google Play crash on app startup with the following error:
```
2021-12-28 08:28:31.847 23118-23118/? E/MainActivity: Failed to create Python app
    java.lang.Exception: Unable to compute Python version
        at org.beeware.android.MainActivity.startPython(MainActivity.java:216)
        at org.beeware.android.MainActivity.onCreate(MainActivity.java:248)
        at android.app.Activity.performCreate(Activity.java:7993)
        at android.app.Activity.performCreate(Activity.java:7982)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**To Reproduce**
1. Create an AAB for the "command" example of Toga, using the Toga code from the master branch [1198c0f] and the briefcase-android-gradle-template code from the dev branch [f251575]
2. Sign the AAB
3. Uplad the AAB to Google Play
4. Install the app from Google Play
5. Run the app

The behaviour can also be tested locally:

1. Create an AAB for the "command" example of Toga, using the Toga code from the master branch [1198c0f] and the briefcase-android-gradle-template code from the dev branch [f251575]
2. Connect your Android phone
2. Run bundletool build-apks with the --connected-device option
3. Run bundletool install-apks 
4. Run the app

**Expected behavior**
An app installed from Google Play must start correctly. This must be true for apps uploaded as APK or AAB.

**Environment:**
 - Operating System: Android 10
 - Python version: 3.8
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: master branch, commit [1198c0f]
   - briefcase-android-gradle-template: dev branch [f251575]

### PR DESCRIPTION
**Pull request by t-arn**
This PR fixes the issue #42

## PR Checklist:

- [x] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by t-arn** [comment]
@freakboy3742 Please review this PR

**Review by freakboy3742 — APPROVED** [review]
👍 Makes sense - thanks for the fix!

**Comment by t-arn** [comment]
@freakboy3742 Russel, the gradle as you changed it, is now incorrect: libpython has always been included in the AAB, but it was not extracted from the APP to the file system.

**Comment by freakboy3742** [comment]
@t-arn I'll update the comment to reflect this. 

As for other approaches: while @paulproteus did the original work for Android support, he did so under contract; as such, while he remains a friend of the project, we can't assume he will be available to address any bugs on an ongoing basis. If there's a better approach, then we should log this as a bug that someone could address.

**Pull request merged**
