### PR TITLE
Added BeewareSpinnerAdapter class

### PR DESCRIPTION
**Pull request by t-arn**
This PR adds org.beeware.android.BeewareSpinnerAdapter which is an extension of ArrayAdapter.
BeewareSpinnerAdapter is used in the toga PR #1393 which implements Selection.set_font() for Android (and Winforms)
https://github.com/beeware/toga/pull/1393

## PR Checklist:

- [x] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by t-arn** [comment]
@freakboy3742 Please review this PR.

**Comment by t-arn** [comment]
hmm...I just realized that the dropdown list has a much smaller line spacing than the original Selection implementation. The items are difficult to hit. How can this be fixed?

**Comment by t-arn** [comment]
> hmm...I just realized that the dropdown list has a much smaller line spacing than the original Selection implementation. The items are difficult to hit.

OK, fixed this problem

**Comment by freakboy3742** [comment]
Closing on the basis that the underlying Toga ticket related to this issue has been closed.

**Pull request closed without merging**
